// Mirrors lib/fields.ts and lib/reports.ts. Duplicated here because Supabase Edge
// Functions bundle each function independently and cannot import outside supabase/functions.
export type Field = { label: string; type?: string; options?: string[]; required?: boolean; when?: [string, string] };
export type Panel = { id: string; title: string; group: string; source?: string; description: string; fields: Field[]; evidence: string[] };
const f = (label: string, type = 'text', required = false): Field => ({ label, type, required });
const s = (label: string, options: string[], required = false): Field => ({ label, type: 'select', options, required });
const yes = (label: string) => s(label, ['Yes', 'No', 'Not Applicable']);
const multi = (label: string, options: string[]): Field => ({ label, type: 'multi', options });
const text = (...labels: string[]) => labels.map(label => f(label));
const notes = (...labels: string[]) => labels.map(label => f(label, 'textarea'));
export const panels: Panel[] = [
  { id: '5.1', title: 'Project-based learning', group: 'Pedagogical approaches', source: 'Annexure-5.1.docx', description: 'List of projects assigned to final-year students, their guides, and supporting reports.', fields: [f('Name of Project guide', 'text', true), f('Name of students', 'textarea', true), f('Student Roll Number(s)'), f('Title of the project', 'text', true), f('Broader subject area covered', 'text', true), yes('Whether collaborative / interdisciplinary'), yes('Whether report is available'), yes('Does it support flipped learning'), { ...f('If yes, kindly mention how', 'textarea'), required: true, when: ['Does it support flipped learning', 'Yes'] }, s('Project Type', ['Final-year project', 'Mini project', 'Research project', 'Other']), yes('Interdisciplinary Project'), yes('Collaborative Project'), ...text('Collaborating Department', 'Collaborating Institute', 'Collaborating Industry'), ...notes('Brief Project Description'), s('Current Status', ['Planned', 'In progress', 'Completed']), yes('Is the project report available in the library?'), ...['Library reference/details', 'Location', 'Report number if applicable'].map(label => ({ ...f(label), when: ['Is the project report available in the library?', 'Yes'] as [string, string] }))], evidence: ['Project Report', 'Project List', 'Guide Allocation Document', 'Collaboration Evidence', 'Other Supporting Documents'] },
  { id: '5.2', title: 'Flipped classroom', group: 'Pedagogical approaches', description: 'Record subject-wise flipped-learning activities. The original Annexure 5.2 template was not supplied.', fields: [f('Subject Name', 'text', true), f('Subject Code'), f('Faculty Name', 'text', true), f('Semester'), f('Topic where flipped learning was implemented', 'text', true), multi('Methodology used', ['Students studied textbook derivations before class and doubts were clarified during class', 'Problems were given as assignments', 'Coding assignments were completed in laboratories', 'Student seminar/presentation', 'Other']), ...notes('Description of implementation'), f('Number of participating students', 'number'), ...notes('Learning activity', 'Outcome/observation')], evidence: ['Lesson Plan', 'Laboratory Manual', 'Assignment', 'Seminar Report', 'Seminar PPT', 'Attendance', 'Photographs', 'Other Evidence'] },
  { id: '5.3', title: 'Student seminars', group: 'Pedagogical approaches', source: 'Annexure-5.3.docx', description: 'Brief report of seminars conducted as part of the student curriculum.', fields: [f('Seminar topic', 'text', true), f('Name of students', 'textarea', true), f('Name of guide', 'text', true), f('Broader subject area', 'text', true), yes('Whether seminar report/ PPT is preserved?'), ...text('Subject Name', 'Subject Code', 'Semester'), f('Seminar Date', 'date'), f('Number of participating students', 'number'), ...notes('Description of implementation', 'Outcome/observation')], evidence: ['Seminar Report', 'Seminar PPT', 'Attendance', 'Photographs', 'Other Evidence'] },
  { id: '5.4', title: 'Application to abstract', group: 'Pedagogical approaches', source: 'Annexure-5.4.docx', description: 'Explain how hardware laboratory experiments help students understand theoretical concepts.', fields: [f('Name of laboratory', 'text', true), f('Name of experiment', 'text', true), yes('Whether implementing the concept'), { ...f('If yes How?', 'textarea'), required: true, when: ['Whether implementing the concept', 'Yes'] }, ...text('Subject Name', 'Subject Code', 'Faculty Name', 'Theoretical Concept'), ...notes('Explanation of how laboratory work helps students understand the theoretical concept', 'Student learning outcome', 'Remarks')], evidence: ['Laboratory Manual', 'Lesson Plan', 'Photographs', 'Other Evidence'] },
  { id: '5.5', title: 'VSK & multimedia support', group: 'Pedagogical approaches', description: 'Classroom and laboratory facilities. Original Annexure 5.5 template was not supplied.', fields: [f('Room/Laboratory Name', 'text', true), f('Room Number'), s('Type of Facility', ['Classroom', 'Laboratory', 'Seminar hall', 'Other']), ...['Smart Board', 'Projector', 'Computer', 'Internet Facility', 'Audio System', 'Video/Multimedia Facility'].map(yes), ...text('Other Technology', 'Subjects/Activities Using the Facility'), s('Frequency of Use', ['Daily', 'Weekly', 'Monthly', 'Occasionally']), ...notes('Remarks')], evidence: ['Photographs', 'Facility Inventory', 'Supporting Documents'] },
  { id: '5.6', title: 'Internships & field projects', group: 'Experiential learning', source: 'Annexure-5.6.docx', description: 'Year-wise internship records with tenure, payment status, and preserved industry documents.', fields: [f('Name of students', 'text', true), f('Roll Number'), f('Year/Semester'), f('Name of company/ institute', 'text', true), f('Tenure of internship', 'text', true), s('Paid/ un paid', ['Paid', 'Unpaid'], true), yes('Does department has all relevant documents?'), ...text('Internship Title', 'Internship Type'), f('Start Date', 'date'), f('End Date', 'date'), ...text('Location', 'Faculty Coordinator'), ...notes('Brief Description', 'Outcome')], evidence: ['Appointment/Offer Letter', 'Internship Completion Certificate', 'Internship Report', 'Release Letter', 'Industry Certificate', 'Photographs', 'Other Evidence'] },
  { id: '5.7', title: 'Slow & advanced learners', group: 'Catering to diversity', source: 'Annexure-5.7.docx', description: 'Record individual learner support, previous and present grades, and signed evidence.', fields: [f('Name of student', 'text', true), f('Name of faculty member', 'text', true), f('Name of subject', 'text', true), f('Topic covered', 'text', true), f('Previous grade'), f('Present grade'), f('Signature of the student', 'signature'), f('Signature of the faculty member', 'signature'), s('Student Category', ['Slow Learner', 'Advanced Learner', 'Backlog Student', 'Other'], true), multi('Type of Intervention', ['Remedial Classes', 'Additional Tutorials', 'Mentoring', 'Extra Assignments', 'Advanced Problems', 'Additional Learning Resources', 'Other Intervention']), f('Number of Students', 'number'), ...notes('Description of Action', 'Outcome', 'Remarks')], evidence: ['Student Results', 'Attendance', 'Improvement Evidence', 'Signature of the student', 'Signature of the faculty member', 'Supporting Documents'] },
  { id: '5.8', title: 'Adaptive teaching methods', group: 'Catering to diversity', description: 'State-of-the-art topics, teaching methods, and relevant library resources. Template not supplied.', fields: [f('Subject', 'text', true), f('Faculty', 'text', true), f('Topic', 'text', true), s('Within Curriculum / Beyond Curriculum', ['Within Curriculum', 'Beyond Curriculum']), ...notes('Reason for Selection', 'Teaching Method'), f('Number of Students', 'number'), ...notes('Learning Outcome'), ...text('Book Title', 'Author', 'Publisher', 'Library Accession Number'), s('Availability', ['Available', 'Unavailable', 'On order'])], evidence: ['Attendance', 'Lesson Plan', 'Geotagged Photos', 'Teaching Material', 'Library Evidence', 'Other Documents'] },
  { id: '5.9a', title: 'SWAYAM / online courses', group: 'Skill development & support', description: 'Annexure 5.9 · Student course enrollments, results, and certificates. Template not supplied.', fields: [f('Student Name', 'text', true), f('Roll Number'), f('SWAYAM/NPTEL Course', 'text', true), ...text('Course Provider', 'Duration'), s('Enrollment Status', ['Enrolled', 'Not enrolled', 'Withdrawn']), s('Completion Status', ['In progress', 'Completed', 'Not completed']), f('Result/Grade'), yes('Certificate Available')], evidence: ['Enrollment Evidence', 'Certificate', 'Result', 'Other Documents'] },
  { id: '5.9b', title: 'Seminars & talks', group: 'Skill development & support', description: 'Annexure 5.9 · Talks organized for skill development. Template not supplied.', fields: [f('Seminar/Talk Title', 'text', true), f('Date', 'date'), f('Speaker', 'text', true), ...text('Speaker Organization', 'Topic'), f('Number of Students', 'number'), ...notes('Description', 'Outcome')], evidence: ['Invitation Letter', 'Leaflet/Brochure', 'Attendance', 'Geotagged Photos', 'Presentation', 'Report'] },
  { id: '5.10', title: 'Industrial training', group: 'Industry–academia linkage', description: 'Student and faculty training with industry. Template not supplied.', fields: [f('Student/Faculty Name', 'text', true), f('Industry', 'text', true), f('Training Title', 'text', true), f('Duration'), f('Start Date', 'date'), f('End Date', 'date'), ...notes('Description', 'Outcome')], evidence: ['Training Certificate', 'Attendance', 'Report', 'Evidence'] },
  { id: '5.11', title: 'Industry collaborative projects', group: 'Industry–academia linkage', description: 'Projects undertaken in collaboration with industry. Template not supplied.', fields: [f('Project Title', 'text', true), f('Student(s)', 'textarea', true), ...text('Faculty Guide'), f('Industry Name', 'text', true), ...text('Industry Contact', 'Project Duration'), ...notes('Description', 'Outcome')], evidence: ['Supporting Documents', 'Project Report', 'Collaboration Evidence'] },
  { id: '5.12', title: 'Industry programs & talks', group: 'Industry–academia linkage', description: 'Joint programs and invited industry talks. Template not supplied.', fields: [f('Program/Talk Name', 'text', true), f('Industry', 'text', true), f('Speaker'), f('Date', 'date'), f('Participants', 'number'), ...notes('Description', 'Outcome')], evidence: ['Evidence', 'Attendance', 'Invitation Letter', 'Photographs'] },
  { id: '5.13', title: 'MoUs with industries', group: 'Industry–academia linkage', description: 'Industry agreements, validity, and activities. Template not supplied.', fields: [f('Industry/Organization', 'text', true), f('MoU Title', 'text', true), f('Date Signed', 'date'), f('Validity'), ...notes('Purpose', 'Activities Conducted'), s('Current Status', ['Active', 'Expired', 'Under renewal'])], evidence: ['Supporting MoU Document', 'Activity Evidence'] },
  { id: 'assessment', title: 'Assessment', group: 'Institutional information', description: 'Assessment practices according to university policy.', fields: [f('Assessment Type', 'text', true), f('Applicable University Policy', 'text', true), ...notes('Description', 'Remarks')], evidence: ['Supporting Document', 'University Policy'] },
  { id: 'grievance', title: 'Academic grievance redressal', group: 'Institutional information', description: 'Feedback committee and examination cell records.', fields: [f('Type of Academic Grievance', 'text', true), f('Number of Cases', 'number', true), f('Source of Data'), ...notes('Action Taken'), s('Status', ['Open', 'In progress', 'Resolved']), ...notes('Remarks')], evidence: ['Feedback Committee Report', 'Examination Cell Paper Review Report', 'Other relevant evidence'] },
  { id: 'gender', title: 'Gender equality', group: 'Institutional information', description: 'Office/coordinator records of gender-equality initiatives.', fields: [f('Activity/Initiative', 'text', true), f('Date', 'date'), ...notes('Description'), f('Number of Participants', 'number'), ...notes('Outcome', 'Remarks')], evidence: ['Supporting Evidence', 'Attendance', 'Photographs'] },
];
export type Entry = { id: string; panel: string; year: string; department: string; respondent: string; designation: string; email: string; date: string; data: Record<string, string | string[]>; status: string; createdBy: string; createdAt: string; updatedAt: string; version: number; comment?: string; sample?: boolean };
export type Evidence = { id: string; entryId: string; name: string; type: string; size: number; year: string; department: string; parameter: string; activity: string; uploadedBy: string; uploadedAt: string; status: string; comments: string };
export function missing(entry: Entry) {
  const p = panels.find(x => x.id === entry.panel);
  if (!p) return ['Unknown panel'];
  return [...['year', 'department', 'respondent', 'designation', 'email', 'date'].filter(k => !String(entry[k as keyof Entry] || '').trim()), ...p.fields.filter(f => f.required && (!f.when || entry.data[f.when[0]] === f.when[1]) && !String(entry.data[f.label] || '').trim()).map(f => f.label)];
}
export type ReportSection = { heading: string; text: string; sources: string[] };
export function compileReport(entries: Entry[], files: Evidence[], filter: { year: string; department: string; parameter: string }): ReportSection[] {
  const rows = entries.filter(e => ['Submitted', 'Department approved', 'Approved'].includes(e.status) && (!filter.year || e.year === filter.year) && (!filter.department || e.department === filter.department) && (!filter.parameter || e.panel === filter.parameter));
  const ids = (es: Entry[]) => es.map(e => e.id); const supported = rows.filter(e => files.some(f => f.entryId === e.id)); const sections: ReportSection[] = [{ heading: 'Executive Summary', text: rows.length ? `${rows.length} submitted records across ${new Set(rows.map(e => e.department)).size} departments and ${new Set(rows.map(e => e.year)).size} academic years. ${rows.filter(e => e.status === 'Approved').length} records have final approval. Counts represent records, not unique students.` : 'Data not provided.', sources: ids(rows) }];
  for (const p of panels.filter(p => !filter.parameter || p.id === filter.parameter)) { const subset = rows.filter(e => e.panel === p.id); let description = subset.length ? `${subset.length} ${p.title.toLowerCase()} record(s) submitted. ${subset.filter(e => files.some(f => f.entryId === e.id)).length} have supporting evidence.` : 'Data not provided.'; if (p.id === '5.1' && subset.length) description += ` ${subset.filter(e => e.data['Interdisciplinary Project'] === 'Yes').length} explicitly marked interdisciplinary; ${subset.filter(e => e.data['Collaborative Project'] === 'Yes').length} explicitly marked collaborative.`; sections.push({ heading: p.title + ' Summary', text: description, sources: ids(subset) }); }
  sections.push({ heading: 'Supporting Evidence Status', text: rows.length ? `${supported.length} of ${rows.length} records have evidence; ${rows.length - supported.length} have evidence missing. ${rows.filter(e => files.some(f => f.entryId === e.id && f.status === 'Verified')).length} have at least one verified document.` : 'Data not provided.', sources: ids(rows) });
  for (const [heading, key] of [['Department-Wise Summary', 'department'], ['Academic-Year-Wise Summary', 'year']] as const) { const values = [...new Set(rows.map(e => e[key]))]; sections.push({ heading, text: values.map(v => `${v}: ${rows.filter(e => e[key] === v).length} submitted records.`).join('\n') || 'Data not provided.', sources: ids(rows) }); }
  const incomplete = rows.filter(e => missing(e).length || !files.some(f => f.entryId === e.id)); sections.push({ heading: 'Missing Information', text: incomplete.length ? incomplete.map(e => `${e.department}, ${e.year}, ${e.panel}: ${missing(e).join(', ') || 'Evidence missing'}.`).join('\n') : rows.length ? 'No missing required information or evidence in selected records.' : 'Data not provided.', sources: ids(incomplete) });
  sections.push({ heading: 'Important Items Requiring Coordinator Follow-Up', text: rows.length ? `${rows.filter(e => e.status !== 'Approved').length} records require final approval. ${rows.filter(e => !files.some(f => f.entryId === e.id && f.status === 'Verified')).length} have no verified evidence. Verify all draft statements against the linked source records.` : 'Data not provided.', sources: ids(rows) });
  return sections;
}
