import {type Entry,initialDepartments} from './fields';
export const demoEntries:Entry[]=[
 ['5.1','Solar-powered smart irrigation','Electrical Engineering','2025–26','Submitted',{'Name of Project guide':'Dr. A. Sen','Name of students':'Sample student A; Sample student B','Broader subject area covered':'Renewable energy','Interdisciplinary Project':'Yes','Collaborative Project':'No'}],
 ['5.3','Applications of machine learning','Computer Science & Engineering','2025–26','Draft',{'Name of guide':'Dr. R. Das','Name of students':'Sample student C','Broader subject area':'Artificial intelligence'}],
 ['5.6','Manufacturing process internship','Mechanical Engineering','2024–25','Submitted',{'Name of students':'Sample student D','Name of company/ institute':'Example Engineering Works','Tenure of internship':'6 weeks','Paid/ un paid':'Unpaid'}],
 ['5.7','Thermodynamics support','Mechanical Engineering','2025–26','Draft',{'Name of student':'Sample student E','Name of faculty member':'Dr. P. Roy','Name of subject':'Thermodynamics','Topic covered':'First law','Previous grade':'D','Present grade':'B','Student Category':'Slow Learner'}],
 ['5.9a','Introduction to textile engineering','Textile Technology','2024–25','Submitted',{'Student Name':'Sample student F','SWAYAM/NPTEL Course':'Introduction to textile engineering','Completion Status':'Completed'}],
 ['5.4','Verification of Ohm’s law','Electrical Engineering','2023–24','Submitted',{'Name of laboratory':'Basic Electrical Engineering','Name of experiment':'Verification of Ohm’s law','Whether implementing the concept':'Yes','If yes How?':'Measure current and voltage to verify the linear relationship.'}]
].map((row,i)=>{const [panel,title,department,year,status,data]=row as [string,string,string,string,string,Record<string,string>];return {id:'demo-'+i,panel,year,department,respondent:'Sample Faculty',designation:'Assistant Professor',email:'faculty@example.edu',date:'2026-09-18',data:{...data,...(panel==='5.1'?{'Title of the project':title}:panel==='5.3'?{'Seminar topic':title}:panel==='5.6'?{'Internship Title':title}:{})},status,createdBy:'demo@example.edu',createdAt:'2026-09-18T09:00:00Z',updatedAt:'2026-09-18T09:00:00Z',version:1,sample:true};});
export const demoState={user:{name:'NAAC Coordinator',email:'demo@example.edu',role:'admin',department:''},entries:demoEntries,evidence:[],departments:initialDepartments,users:[],audit:[],reports:[]};
