import {panels,panelLabel,titleOf,type Entry,type Evidence} from './fields';
import type {Report} from './reports';
export function download(data:Blob|BlobPart,name:string,type='application/octet-stream'){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
const safe=(s:string)=>/^[=+@\-\t\r]/.test(s)?"'"+s:s;
export async function exportEntries(entries:Entry[],files:Evidence[],format:string){
 const rows=entries.map(e=>({'Record ID':e.id,'Annexure':panelLabel(e.panel),'Parameter':panels.find(p=>p.id===e.panel)?.title||e.panel,'Academic Year':e.year,'Department':e.department,'Respondent':e.respondent,'Designation':e.designation,'Email':e.email,'Submission Date':e.date,'Title':titleOf(e),'Status':e.status,'Evidence':files.some(f=>f.entryId===e.id)?'Evidence Available':'Evidence Missing',...Object.fromEntries(Object.entries(e.data).map(([k,v])=>[k,Array.isArray(v)?v.join('; '):v]))}));
 if(format==='csv'){const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const quote=(s:unknown)=>'"'+safe(String(s??'')).replaceAll('"','""')+'"';download('\uFEFF'+[keys.map(quote).join(','),...rows.map(r=>keys.map(k=>quote((r as Record<string,unknown>)[k])).join(','))].join('\r\n'),'naac-records.csv','text/csv;charset=utf-8');}
 if(format==='xlsx'){const ExcelJS=await import('exceljs');const book=new ExcelJS.Workbook();for(const p of panels){const es=rows.filter(r=>r.Parameter===p.title);if(!es.length)continue;const sheet=book.addWorksheet(p.id);const keys=[...new Set(es.flatMap(r=>Object.keys(r)))];sheet.columns=keys.map(k=>({header:k,key:k,width:28}));for(const row of es)sheet.addRow(row);sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF175548'}};sheet.views=[{state:'frozen',ySplit:1}];}if(!book.worksheets.length)book.addWorksheet('No records');download(new Blob([await book.xlsx.writeBuffer() as ArrayBuffer]),'naac-annexures.xlsx');}
}
export async function exportReport(report:Report,format:string){const title=report.title;const status=report.status==='Approved'?'Approved by NAAC Coordinator':report.mode+' Draft — Verification by NAAC Coordinator Required';const scope=`${report.department||'All departments'} · ${report.year||'All academic years'}`;const paragraphs=[title,status,scope,...report.sections.flatMap(s=>[s.heading,s.text,'Source records: '+(s.sources.join(', ')||'Data not provided.')])];
 if(format==='pdf'){const {jsPDF}=await import('jspdf');const pdf=new jsPDF();let y=20;for(const [i,p] of paragraphs.entries()){pdf.setFontSize(i===0?18:10);const lines=pdf.splitTextToSize(p.replace(/[–—]/g,'-'),175);for(const line of lines){if(y>277){pdf.addPage();y=20;}pdf.text(line,18,y);y+=5;}y+=5;}pdf.save('naac-point-5-report.pdf');}
 if(format==='docx'){const {Document,Packer,Paragraph,HeadingLevel}=await import('docx');const doc=new Document({sections:[{children:[new Paragraph({text:title,heading:HeadingLevel.TITLE}),new Paragraph(status),new Paragraph(scope),...report.sections.flatMap(s=>[new Paragraph({text:s.heading,heading:HeadingLevel.HEADING_1}),...s.text.split('\n').map(text=>new Paragraph(text)),new Paragraph('Source records: '+(s.sources.join(', ')||'Data not provided.'))])]}]});download(await Packer.toBlob(doc),'naac-point-5-report.docx');}
}
