import {panels,type Entry,type Evidence,missing} from './fields';
export type ReportSection={heading:string;text:string;sources:string[]};
export type Report={id:string;title:string;year:string;department:string;parameter:string;mode:string;status:string;sections:ReportSection[];createdAt:string;createdBy:string;version:number;sourceSnapshots:{entry:Entry;evidence:Evidence[]}[];comment?:string};
export function compileReport(entries:Entry[],files:Evidence[],filter:{year:string;department:string;parameter:string}):ReportSection[]{
 const rows=entries.filter(e=>['Submitted','Department approved','Approved'].includes(e.status)&&(!filter.year||e.year===filter.year)&&(!filter.department||e.department===filter.department)&&(!filter.parameter||e.panel===filter.parameter));
 const ids=(es:Entry[])=>es.map(e=>e.id);const supported=rows.filter(e=>files.some(f=>f.entryId===e.id));const sections:ReportSection[]=[{heading:'Executive Summary',text:rows.length?`${rows.length} submitted records across ${new Set(rows.map(e=>e.department)).size} departments and ${new Set(rows.map(e=>e.year)).size} academic years. ${rows.filter(e=>e.status==='Approved').length} records have final approval. Counts represent records, not unique students.`:'Data not provided.',sources:ids(rows)}];
 for(const p of panels.filter(p=>!filter.parameter||p.id===filter.parameter)){const subset=rows.filter(e=>e.panel===p.id);let description=subset.length?`${subset.length} ${p.title.toLowerCase()} record(s) submitted. ${subset.filter(e=>files.some(f=>f.entryId===e.id)).length} have supporting evidence.`:'Data not provided.';if(p.id==='5.1'&&subset.length)description+=` ${subset.filter(e=>e.data['Interdisciplinary Project']==='Yes').length} explicitly marked interdisciplinary; ${subset.filter(e=>e.data['Collaborative Project']==='Yes').length} explicitly marked collaborative.`;sections.push({heading:p.title+' Summary',text:description,sources:ids(subset)});}
 sections.push({heading:'Supporting Evidence Status',text:rows.length?`${supported.length} of ${rows.length} records have evidence; ${rows.length-supported.length} have evidence missing. ${rows.filter(e=>files.some(f=>f.entryId===e.id&&f.status==='Verified')).length} have at least one verified document.`:'Data not provided.',sources:ids(rows)});
 for(const [heading,key] of [['Department-Wise Summary','department'],['Academic-Year-Wise Summary','year']] as const){const values=[...new Set(rows.map(e=>e[key]))];sections.push({heading,text:values.map(v=>`${v}: ${rows.filter(e=>e[key]===v).length} submitted records.`).join('\n')||'Data not provided.',sources:ids(rows)});}
 const incomplete=rows.filter(e=>missing(e).length||!files.some(f=>f.entryId===e.id));sections.push({heading:'Missing Information',text:incomplete.length?incomplete.map(e=>`${e.department}, ${e.year}, ${e.panel}: ${missing(e).join(', ')||'Evidence missing'}.`).join('\n'):rows.length?'No missing required information or evidence in selected records.':'Data not provided.',sources:ids(incomplete)});
 sections.push({heading:'Important Items Requiring Coordinator Follow-Up',text:rows.length?`${rows.filter(e=>e.status!=='Approved').length} records require final approval. ${rows.filter(e=>!files.some(f=>f.entryId===e.id&&f.status==='Verified')).length} have no verified evidence. Verify all draft statements against the linked source records.`:'Data not provided.',sources:ids(rows)});return sections;
}
