import { audit,canEdit,canReview,db,evidence,failure,guardOrigin,HttpError,id,identity,json,now,record,records,requireAdmin,setup } from '../../../lib/server';
import {missing,panels,years,type Entry} from '../../../lib/fields';
export async function GET(req:Request){try{const u=await identity(req);await setup();const entries=await records(u);const files=await evidence(u);const departments=(await db().prepare('SELECT name FROM departments ORDER BY name').all()).results.map((x:any)=>x.name);const users=u.role==='admin'?(await db().prepare('SELECT email,name,role,department FROM users').all()).results:[];const log=u.role==='admin'?(await db().prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200').all()).results:[];const reportRows=u.role==='admin'?await db().prepare('SELECT payload FROM ai_summaries ORDER BY created_at DESC').all():await db().prepare('SELECT payload FROM ai_summaries WHERE created_by = ? ORDER BY created_at DESC').bind(u.email).all();return json({user:u,entries,evidence:files,departments,users,audit:log,reports:reportRows.results.map((r:any)=>JSON.parse(r.payload))});}catch(e){return failure(e);}}
export async function POST(req:Request){try{guardOrigin(req);const u=await identity(req);const b=await req.json();const t=now();
 if(b.action==='department'){requireAdmin(u);const name=String(b.name||'').trim();if(!name||name.length>120)throw new HttpError('Enter a department name.');await db().prepare('INSERT INTO departments VALUES (?,?)').bind(name,t).run();await audit(u,'Department added',name);return json({ok:true});}
 if(b.action==='user'){requireAdmin(u);if(!['admin','coordinator','respondent'].includes(b.role)||!/^\S+@\S+\.\S+$/.test(b.email))throw new HttpError('Enter a valid email and role.');if(b.email.toLowerCase()===u.email&&b.role!=='admin')throw new HttpError('You cannot remove your own administrator access.');if(b.role!=='admin'&&!await db().prepare('SELECT name FROM departments WHERE name=?').bind(b.department).first())throw new HttpError('Select a valid department.');await db().prepare('INSERT INTO users VALUES (?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,department=excluded.department,updated_at=excluded.updated_at').bind(b.email.toLowerCase(),String(b.name||b.email),b.role,b.department||'',t,t).run();await audit(u,'User access updated',b.email);return json({ok:true});}
 if(b.action==='review'){const e=await record(u,b.id);if(!canReview(u,e))throw new HttpError('Coordinator access required.',403);if(!['Submitted','Department approved'].includes(e.status)||!['Department approved','Approved','Returned'].includes(b.status))throw new HttpError('Invalid review transition.');if(b.status==='Approved'&&u.role!=='admin')throw new HttpError('Final approval requires the NAAC coordinator.',403);if(b.status==='Returned'&&!String(b.comment||'').trim())throw new HttpError('Explain the correction required.');if(b.status!=='Returned'){if(missing(e).length)throw new HttpError('Required information is missing.');if(!(await evidence(u)).some(f=>f.entryId===e.id&&f.status==='Verified'))throw new HttpError('Verify at least one supporting document before approval.');}const revised={...e,status:b.status,comment:String(b.comment||''),updatedAt:t,version:e.version+1};await db().batch([db().prepare('UPDATE submissions SET status=?,payload=?,updated_at=?,version=? WHERE id=? AND version=?').bind(revised.status,JSON.stringify(revised),t,revised.version,e.id,e.version),db().prepare('INSERT INTO coordinator_reviews VALUES (?,?,?,?,?,?)').bind(id(),e.id,b.status,revised.comment,t,u.email),db().prepare('INSERT INTO audit_logs VALUES (?,?,?,?,?)').bind(id(),'Submission '+b.status,e.id,t,u.email)]);return json({entry:revised});}
 if(b.action==='save'||b.action==='submit'){
 const raw=b.entry as Entry;const panel=panels.find(p=>p.id===raw?.panel);if(!panel||!years.includes(raw.year))throw new HttpError('Select an annexure and academic year.');if(!await db().prepare('SELECT name FROM departments WHERE name=?').bind(raw.department).first())throw new HttpError('Select a valid department.');if(u.role!=='admin'&&raw.department!==u.department)throw new HttpError('You can only submit for your department.',403);if(raw.panel==='gender'&&u.role==='respondent')throw new HttpError('Gender-equality data is restricted to coordinators.',403);
 const old=raw.id?await record(u,raw.id):null;if(old&&!canEdit(u,old))throw new HttpError('Submitted data is locked. Return the record for correction first.',403);if(old&&raw.version!==old.version)throw new HttpError('This record changed. Reload before saving.',409);if(old&&(raw.panel!==old.panel||raw.year!==old.year||raw.department!==old.department)&&(await evidence(u)).some(f=>f.entryId===old.id))throw new HttpError('Records with preserved evidence cannot change annexure, year, or department. Create a separate record.');
 const data:Record<string,string|string[]>={};for(const f of panel.fields){const v=raw.data?.[f.label];if(v!==undefined){if(f.type==='multi'){if(!Array.isArray(v)||v.some(x=>!f.options?.includes(x)))throw new HttpError('Invalid selection: '+f.label);data[f.label]=v;}else{if(typeof v!=='string'||v.length>12000)throw new HttpError('Invalid value: '+f.label);if(f.options&&v&&!f.options.includes(v))throw new HttpError('Invalid option: '+f.label);if(f.type==='number'&&v&&(!Number.isFinite(Number(v))||Number(v)<0||!Number.isInteger(Number(v))))throw new HttpError('Enter a non-negative whole number: '+f.label);data[f.label]=v;}}}
 if(data['Start Date']&&data['End Date']&&data['End Date']<data['Start Date'])throw new HttpError('End date must follow start date.');
 const entry:Entry={id:old?.id||id(),panel:raw.panel,year:raw.year,department:raw.department,respondent:String(raw.respondent||'').slice(0,200),designation:String(raw.designation||'').slice(0,200),email:String(raw.email||'').slice(0,200),date:String(raw.date||''),data,status:b.action==='submit'?'Submitted':'Draft',createdBy:old?.createdBy||u.email,createdAt:old?.createdAt||t,updatedAt:t,version:(old?.version||0)+1};
 if(b.action==='submit'){const fields=missing(entry);if(fields.length)throw new HttpError('Complete required fields: '+fields.join(', '));if(!/^\S+@\S+\.\S+$/.test(entry.email))throw new HttpError('Enter a valid respondent email.');if(!/^\d{4}-\d{2}-\d{2}$/.test(entry.date))throw new HttpError('Enter a valid submission date.');}
 if(old){const result=await db().prepare('UPDATE submissions SET panel=?,year=?,department=?,status=?,payload=?,version=?,updated_at=? WHERE id=? AND version=?').bind(entry.panel,entry.year,entry.department,entry.status,JSON.stringify(entry),entry.version,t,entry.id,old.version).run();if(!result.meta.changes)throw new HttpError('Concurrent change detected. Reload before saving.',409);}else{await db().prepare('INSERT INTO submissions VALUES (?,?,?,?,?,?,?,?,?,?)').bind(entry.id,entry.panel,entry.year,entry.department,entry.createdBy,entry.status,JSON.stringify(entry),entry.version,entry.createdAt,t).run();}
 if(b.action==='submit')await db().prepare('INSERT INTO submission_revisions VALUES (?,?,?,?,?)').bind(id(),entry.id,JSON.stringify({entry,evidence:(await evidence(u)).filter(f=>f.entryId===entry.id)}),t,u.email).run();await audit(u,b.action==='submit'?'Submission finalized':'Draft saved',entry.id);return json({entry});}
 if(b.action==='history'){const e=await record(u,b.id);const rows=await db().prepare('SELECT payload,created_at,created_by FROM submission_revisions WHERE submission_id=? ORDER BY created_at DESC').bind(e.id).all();return json({history:rows.results.map((r:any)=>({...r,payload:JSON.parse(r.payload)}))});}
 if(b.action==='backup'){requireAdmin(u);const result:any={exportedAt:t};for(const table of ['departments','academic_years','users','submissions','submission_revisions','evidence_documents','coordinator_reviews','ai_summaries','audit_logs'])result[table]=(await db().prepare('SELECT * FROM '+table).all()).results;await audit(u,'Backup exported','database');return json(result);}
 throw new HttpError('Unknown action.');
 }catch(e){return failure(e);}}
